# I really just have issues with the automatic "semantic blocks"
# Sort of a more specific case for a dev to figure out

format: progress
ruby_version: 2.5

ignore:
  - '**/*':
    - Standard/SemanticBlocks
