# Test runner copied from R167/backblaze
name: CI
on:
  push:
    branches:
      - master
      # Temp include the rewrite branch
      - complete-rewrite
    tags:
      - v*
  pull_request:
env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
jobs:
  specs:
    name: ${{ matrix.job }} ruby-${{ matrix.ruby }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ "2.5", "2.6", "2.7", "3.0" ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: bundler gem cache
        uses: actions/cache@v1
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-
            bundle-use-ruby-${{ matrix.os }}-
      - name: install dependencies
        run:  bundle update --group runtime # This updates all runtime dependencies
      - name: specs
        run:  bundle exec rake spec
